# Generated by Django 5.1.1 on 2024-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slider_item', models.ManyToManyField(to='allImages.slideritem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
