# Generated by Django 5.1.1 on 2024-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_names',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
