# Generated by Django 5.1.1 on 2024-10-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_checkout_product_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='product_quantities',
            field=models.JSONField(default=dict),
        ),
    ]
